import{readFileSync,existsSync}from'node:fs';import{grade7Unit5Lessons,grade7Unit5Slugs}from'../src/data/grade7Unit5.ts';import{grade7Unit5UnitCheckBank}from'../src/data/grade7Unit5UnitCheck.ts';
let checks=0;const ok=(x:any,m:string)=>{checks++;if(!x)throw Error(`Unit 5 audit failed: ${m}`)},ids=new Set<string>();
ok(grade7Unit5Lessons.length===7,'seven lessons');ok(grade7Unit5UnitCheckBank.length===40,'40 Unit Check questions');ok(new Set(grade7Unit5Slugs).size===7,'unique slugs');
for(const [li,l] of grade7Unit5Lessons.entries()){ok(l.number===`5.${li+1}`,`${l.slug} sequence`);ok(l.outcome.includes('N5'),`${l.slug} N5`);ok(l.practice.length===8,`${l.slug} eight practice`);ok(l.check.length===30,` 30 check`);ok(new Set(l.check.map(x=>x.prompt)).size===30,` 30 distinct prompts`);ok(l.exit.length===3,`${l.slug} three exit`);ok(l.understand.length===4,`${l.slug} four concepts`);ok(l.examples.length===4,`${l.slug} four examples`);ok(l.explore.phases.length===5,`${l.slug} five phases`);ok(l.apply.values.length===4,`${l.slug} apply calculations`);const pools=[['warm',[l.warmup]],['practice',l.practice],['check',l.check],['exit',l.exit]] as const;for(const[p,items]of pools)for(const q of items){ok(!ids.has(q.id),`${q.id} globally unique`);ids.add(q.id);ok(q.choices.length>0,`${q.id} options`);ok(q.answer>=0&&q.answer<q.choices.length,`${q.id} answer position`);ok(!!q.feedback,`${q.id} feedback`);ok(!!q.hint&&!!q.hint2&&q.hint!==q.hint2,`${q.id} question-specific hints`);ok(!!q.route,`${q.id} repair route`);if(q.responseType==='multi-select')ok((q.answers?.length||0)>=2,`${q.id} multi answers`);if(q.responseType==='order')ok(q.orderTokens?.length===q.orderAnswer?.length,`${q.id} order state`)}ok(!l.practice.some(a=>a.prompt===l.warmup.prompt),`${l.slug} readiness separation`);ok(!l.exit.some(a=>l.practice.some(b=>a.prompt===b.prompt)),`${l.slug} exit separation`)}
for(const q of grade7Unit5UnitCheckBank){ok(!ids.has(q.id),`${q.id} separate Unit Check id`);ids.add(q.id);ok(!!q.repairLabel&&q.repairLabel.includes('Understand:'),`${q.id} exact repair label`);ok(/^\.\.\//.test(q.route),`${q.id} review route`)}
const categories=[...new Set(grade7Unit5UnitCheckBank.map(x=>x.category))];ok(categories.length===7,'Unit Check all lessons');for(let run=0;run<10000;run++){const chosen=categories.map(c=>grade7Unit5UnitCheckBank.filter(x=>x.category===c)[run%grade7Unit5UnitCheckBank.filter(x=>x.category===c).length]);const extras=[0,1,2].map(k=>grade7Unit5UnitCheckBank.filter(x=>x.category===categories[(run+k)%7])[(run+k+1)%grade7Unit5UnitCheckBank.filter(x=>x.category===categories[(run+k)%7]).length]);const attempt=[...chosen,...extras];ok(attempt.length===10,`balance ${run}`);ok(new Set(attempt.map(x=>x.id)).size===10,`unique attempt ${run}`);ok(new Set(attempt.map(x=>x.category)).size===7,`coverage ${run}`)}
const positions=[0,0,0,0];let seed=505;for(let i=0;i<100000;i++){seed=(seed*1664525+1013904223)>>>0;positions[seed%4]++}positions.forEach((n,i)=>ok(n>24000&&n<26000,`shuffle position ${i}`));
const files=['src/components/Grade7Unit5Explore.astro','src/components/Grade7Unit5Apply.astro','src/components/Grade7Unit5Check.astro','src/components/Grade7Unit5Arcade.astro','src/pages/courses/grade-7-math/operations-fractions/unit-review.astro'];for(const file of files){ok(existsSync(file),`${file} exists`);const s=readFileSync(file,'utf8');for(const token of['role="status"','prefers-reduced-motion','max-width:390px'])ok(s.includes(token),`${file} ${token}`)}
const explore=readFileSync(files[0],'utf8');for(const token of['role="tablist"','role="tab"','role="tabpanel"','ArrowRight','Home','End','invalidate','data-transcript','data-repair','data-checkpoint'])ok(explore.includes(token),`Explore ${token}`);const apply=readFileSync(files[1],'utf8');for(const token of['data-estimate','data-model-quantity','data-comparison','data-decision','invalidate','Written explanations'])ok(apply.includes(token),`Apply ${token}`);const arcade=readFileSync(files[3],'utf8');for(const token of['five stages verified','invalidate','data-final-value','data-final-model','data-plan'])ok(arcade.toLowerCase().includes(token.toLowerCase()),`Arcade ${token}`);
for(const slug of grade7Unit5Slugs)ok(existsSync(`dist/courses/grade-7-math/operations-fractions/${slug}/index.html`),`${slug} built`);ok(existsSync('dist/courses/grade-7-math/operations-fractions/unit-review/index.html'),'review built');
console.log(`Grade 7 Unit 5 audit: ${checks.toLocaleString()} checks passed.`);console.log(`Answer-position simulation: ${positions.join(', ')} across 100,000 shuffles.`);
