// @ts-nocheck
import { readFileSync, existsSync } from 'node:fs';
import { grade7Unit2Lessons } from '../src/data/grade7Unit2.ts';
import { grade7Unit2UnitCheckBank } from '../src/data/grade7Unit2UnitCheck.ts';

let checks=0;
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(`Unit 2 audit failed: ${message}`);checks++;};
const root=new URL('../',import.meta.url);
const read=(path:string)=>readFileSync(new URL(path,root),'utf8');
const normalize=(s:string)=>s.toLowerCase().replace(/[^a-z0-9+-]+/g,' ').trim();
const validateQuestion=(item:any,label:string)=>{assert(typeof item.prompt==='string'&&item.prompt.length>5,`${label} prompt`);assert(Array.isArray(item.choices)&&item.choices.length>=3,`${label} choices`);assert(Number.isInteger(item.answer)&&item.answer>=0&&item.answer<item.choices.length,`${label} answer index`);if(item.answers)assert(item.answers.length>1&&item.answers.every((x:number)=>Number.isInteger(x)&&x>=0&&x<item.choices.length),`${label} multi-select answers`);assert(new Set(item.choices).size===item.choices.length,`${label} unique choices`);assert(item.feedback?.length>8,`${label} instructional feedback`);};

assert(grade7Unit2Lessons.length===5,'five lessons');
const expectedSlugs=['representing-integers','adding-integers-tiles','adding-integers-number-line','subtracting-integers-tiles','subtracting-integers-number-line'];
assert(grade7Unit2Lessons.map(x=>x.slug).join('|')===expectedSlugs.join('|'),'approved lesson order');
const allPrompts=new Map<string,string>();
const exploreCounts=[5,6,7,8,8];
for(const [lessonIndex,lesson] of grade7Unit2Lessons.entries()){
  assert(lesson.number.startsWith('2.'),`${lesson.number} numbering`);assert(lesson.outcome.includes('N6'),`${lesson.number} N6 alignment`);
  assert(lesson.goals.length>=5,`${lesson.number} goals`);assert(lesson.understand.length>=5,`${lesson.number} understand depth`);assert(lesson.examples.length>=4,`${lesson.number} examples`);
  assert(lesson.practice.length===8,`${lesson.number} eight supported questions`);assert(lesson.check.length===30,`${lesson.number} 30-item bank`);assert(lesson.exit.length===3,`${lesson.number} three-item exit`);
  assert(lesson.applySupport.checks.length>=3,`${lesson.number} application validation`);assert(lesson.next!==null,`${lesson.number} forward navigation`);
  assert(lesson.explore.phases.length===exploreCounts[lessonIndex],`${lesson.number} approved Explore phase count`);
  const categoryCounts=new Map<string,number>();lesson.check.forEach(x=>categoryCounts.set(x.category||'',(categoryCounts.get(x.category||'')||0)+1));assert(categoryCounts.size===5&&[...categoryCounts.values()].every(x=>x===6),`${lesson.number} balanced check strands`);
  const positions=new Set(lesson.check.map(x=>x.answer));assert(positions.size>=3,`${lesson.number} varied correct-answer positions`);
  [...lesson.practice,...lesson.check,...lesson.exit].forEach((item,i)=>{validateQuestion(item,`${lesson.number} item ${i+1}`);const key=normalize(item.prompt);assert(!allPrompts.has(key),`${lesson.number} duplicate prompt with ${allPrompts.get(key)}`);allPrompts.set(key,lesson.number);});
}
assert(grade7Unit2Lessons.reduce((n,x)=>n+x.practice.length,0)===40,'40 supported lesson questions');
assert(grade7Unit2Lessons.reduce((n,x)=>n+x.check.length,0)===150,'150 lesson Check Yourself questions');
assert(grade7Unit2Lessons.reduce((n,x)=>n+x.exit.length,0)===15,'15 exit questions');
assert(grade7Unit2UnitCheckBank.length===40,'40-item independent Unit Check');
grade7Unit2UnitCheckBank.forEach((item,i)=>{validateQuestion(item,`unit item ${i+1}`);assert(item.route?.startsWith('../'),`unit item ${i+1} exact lesson route`);assert(!allPrompts.has(normalize(item.prompt)),`unit item ${i+1} separate from lesson pools`);});
for(const lesson of ['Lesson 2.1','Lesson 2.2','Lesson 2.3','Lesson 2.4','Lesson 2.5'])assert(grade7Unit2UnitCheckBank.filter(x=>x.category===lesson).length===8,`${lesson} has eight Unit Check questions`);
for(const position of [0,1,2,3])assert(grade7Unit2UnitCheckBank.filter(x=>x.answer===position).length===10,`Unit Check answer position ${position+1} appears ten times`);
const review=read('src/pages/courses/grade-7-math/integers/unit-review.astro');
const between=(a:string,b:string)=>review.split(a)[1]?.split(b)[0]||'';
assert((between('const routeFinder=[','const practice:').match(/\bq\(/g)||[]).length===5,'five Quick Route Finder questions');
assert((between('const practice:','const repairs:').match(/\bq\(/g)||[]).length===20,'20 supported review questions');
assert((between('const repairs:','---\n<BaseLayout').match(/\bq\(/g)||[]).length===10,'ten misconception repairs');
const reviewPrompts=[...between('const routeFinder=[','---\n<BaseLayout').matchAll(/\bq\('([^']+)'/g)].map(x=>normalize(x[1]));
assert(new Set(reviewPrompts).size===reviewPrompts.length,'review and repair prompts are mutually distinct');
reviewPrompts.forEach(prompt=>assert(!allPrompts.has(prompt),'review prompts separate from lesson pools'));
['overview','targeted-review','practice','repair','check','arcade','finish'].forEach(id=>assert(review.includes(`id="${id}"`),`review section ${id}`));
assert(review.includes('balancedUnit={true}')&&review.includes('count={10}'),'ten-question balanced Unit Check');
const arcade=read('src/components/Grade7Unit2Arcade.astro');
assert((arcade.match(/data-stage="[1-5]"/g)||[]).length===5,'five Temperature Rescue stages');
['data-expected="5,-3,2"','data-expected="-6"','data-expected="0"','data-expected="2"','data-final-plan','data-expected="-3,6,-1"','Starting negative chips','Line start','not judged by keywords or length'].forEach(token=>assert(arcade.includes(token),`arcade final validation ${token}`));
assert(!arcade.includes('.length<')&&!arcade.includes('.includes('),'Arcade has no length or keyword-matching completion rule');
const lessonPage=read('src/components/Grade7Unit2LessonPage.astro');
const applySource=read('src/components/Grade7Unit2Apply.astro');
['overview','big-ideas','understand','examples','vocabulary','explore','practise','check','apply','review'].forEach(id=>assert(lessonPage.includes(`id="${id}"`),`lesson section ${id}`));
['data-warmup','data-unit2-apply','data-exit-ticket','prefers-reduced-motion'].forEach(token=>assert(lessonPage.includes(token)||applySource.includes(token)||read('src/components/Grade7Unit2Explore.astro').includes(token),`interaction safeguard ${token}`));
const explore=read('src/components/Grade7Unit2Explore.astro');const check=read('src/components/Grade7Unit2Check.astro');const practiceSource=read('src/components/Grade7Unit2Practice.astro');
['ArrowRight','ArrowLeft','Home','End','role="tabpanel"','aria-live="polite"','data-checkpoint-passed'].forEach(token=>assert(explore.includes(token)||explore.includes(token.replace('data-checkpoint-passed','checkpointPassed')),`Explore keyboard/status ${token}`));
['data-verify-composer','data-load','data-combine','data-cancel','data-draw','data-build-start','data-add-pairs','data-remove','data-compare','scaled-line','compare-models'].forEach(token=>assert(explore.includes(token),`distinct Explore control ${token}`));
assert(!explore.includes('text.length')&&!explore.includes('hasNumber'),'Explore has no response-length completion rule');
['randomizeChoices','balanced','slice(0,2)','Complete the full set before submitting','Correct answer:'].forEach(token=>assert(check.includes(token),`Check behavior ${token}`));
['data-response="multi"','data-response="number"','data-response="order"','lessonScores','disabled=true','render(true)'].forEach(token=>assert(check.includes(token),`varied Check behavior ${token}`));
['Hint 1','Hint 2','min-height:44px','@media(max-width:620px)'].forEach(token=>assert(practiceSource.includes(token),`practice accessibility ${token}`));
['@media(max-width:700px)','grid-template-columns:1fr','min-height:44px'].forEach(token=>assert(lessonPage.includes(token),`lesson responsive safeguard ${token}`));
assert(!applySource.includes('length>=25')&&!applySource.includes('length>=70'),'application has no word-count completion rule');
assert(lessonPage.includes('Suggested two-session core route')&&applySource.includes('CONSOLIDATION OR EXTENSION'),'realistic core and extension pacing');
assert(grade7Unit2Lessons[0].vocabulary.some(x=>x.term==='positive integer')&&grade7Unit2Lessons[0].vocabulary.some(x=>x.term==='negative integer'),'positive and negative integer vocabulary');
assert(grade7Unit2UnitCheckBank.some(x=>x.kind==='multi-select'&&x.answers?.length===4),'genuine multi-select item');
assert(grade7Unit2UnitCheckBank.some(x=>x.kind==='order'),'ordering item');
assert(grade7Unit2UnitCheckBank.some(x=>x.kind==='construction'),'model construction or selection item');
['@media(max-width:700px)','grid-template-columns:1fr'].forEach(token=>assert(review.includes(token),`review responsive safeguard ${token}`));
for(const slug of expectedSlugs)assert(existsSync(new URL(`dist/courses/grade-7-math/integers/${slug}/index.html`,root)),`built route ${slug}`);
assert(existsSync(new URL('dist/courses/grade-7-math/integers/unit-review/index.html',root)),'built review route');
console.log(`Grade 7 Unit 2 content audit: ${checks} checks passed.`);
