import{existsSync,readFileSync}from'node:fs';import{grade7Unit7Lessons,grade7Unit7Slugs}from'../src/data/grade7Unit7Content.ts';import{grade7Unit7UnitCheckBank}from'../src/data/grade7Unit7UnitCheck.ts';
let checks=0;const ok=(x:any,m:string)=>{checks++;if(!x)throw Error(`Unit 7 audit failed: ${m}`)};const eq=(a:number,b:number,t=1e-9)=>Math.abs(a-b)<=t;
const titles=['Mean and Mode','Median and Range','The Effects of Outliers on Average','Applications of Averages','Different Ways to Express Probability','Tree Diagrams and Two-Event Experiments'];const outcomes=['SP1','SP1','SP2','SP1, SP2','SP4','SP5, SP6'];
ok(grade7Unit7Lessons.length===6,'six lessons');ok(new Set(grade7Unit7Slugs).size===6,'unique slugs');ok(grade7Unit7UnitCheckBank.length===40,'40-question Unit Check');
const allIds=new Set<string>(),checkPrompts=new Set<string>(),practicePrompts=new Set<string>(),exitPrompts=new Set<string>();
for(const[l,lesson]of grade7Unit7Lessons.entries()){
 ok(lesson.number===`7.${l+1}`,`${lesson.slug} sequence`);ok(lesson.title===titles[l],`${lesson.slug} exact title`);ok(lesson.outcome===outcomes[l],`${lesson.slug} exact outcome`);ok(lesson.practice.length===8,`${lesson.slug} eight supported practice`);ok(lesson.check.length===30,`${lesson.slug} 30 Check Yourself`);ok(new Set(lesson.check.map(q=>q.prompt)).size===30,`${lesson.slug} mathematically distinct Check prompts`);ok(lesson.exit.length===3,`${lesson.slug} three exits`);ok(lesson.understand.length===4,`${lesson.slug} four Understand concepts`);ok(lesson.examples.length===4,`${lesson.slug} four worked examples`);ok(lesson.explore.phases.map(x=>x.title).join('|')==='Predict|Build|Verify|Repair|Create',`${lesson.slug} five-phase Explore`);ok(lesson.bigIdeas.length>=2,`${lesson.slug} big ideas`);ok(lesson.prerequisites.length>=3,`${lesson.slug} readiness prerequisites`);ok(lesson.readiness.length>=4,`${lesson.slug} readiness guidance`);
 for(const q of[lesson.warmup,...lesson.practice,...lesson.check,...lesson.exit]){ok(!allIds.has(q.id),`${q.id} globally unique`);allIds.add(q.id);ok(q.choices.length>=4,`${q.id} has response options`);ok(q.answer>=0&&q.answer<q.choices.length,`${q.id} valid answer index`);ok(!!q.feedback&&!!q.hint&&!!q.hint2&&q.hint!==q.hint2,`${q.id} feedback and two distinct hints`);ok(!!q.route,`${q.id} exact repair route`)}
 for(const q of lesson.practice){practicePrompts.add(q.prompt);ok(q.hint.includes(q.prompt),`${q.id} Hint 1 question-specific`);ok(q.hint2.includes('this question'),`${q.id} Hint 2 question-specific`)}for(const q of lesson.exit)exitPrompts.add(q.prompt);for(const q of lesson.check)checkPrompts.add(q.prompt);
 ok(!lesson.practice.some(q=>lesson.check.some(c=>c.prompt===q.prompt)),`${lesson.slug} practice separate from Check`);ok(!lesson.exit.some(q=>lesson.check.some(c=>c.prompt===q.prompt)||lesson.practice.some(p=>p.prompt===q.prompt)),`${lesson.slug} exits separate from other pools`);
 const types=new Set(lesson.check.map(q=>q.responseType));ok(types.size>=3,`${lesson.slug} varied Check response types`);ok(lesson.check.filter(q=>q.visual).length>=8,`${lesson.slug} rendered Check models`);
 const a=lesson.apply;for(const[k,v]of Object.entries({calculations:a.calculations,representations:a.validRepresentations,labels:a.validLabels,scales:a.validScales,units:a.validUnits,comparisons:a.validComparisons,interpretations:a.validInterpretations,predictions:a.validPredictions,decisions:a.validDecisions}))ok(v.length>0,`${lesson.slug} Apply ${k}`);
 ok(lesson.explore.config.validRepresentations.length>=2,`${lesson.slug} Explore equivalent valid representations`);ok(lesson.explore.config.validCreateRepresentations.length>=2,`${lesson.slug} Explore alternate creation representations`);
}
for(const q of grade7Unit7UnitCheckBank){ok(!allIds.has(q.id),`${q.id} Unit Check separate ID`);allIds.add(q.id);ok(!checkPrompts.has(q.prompt)&&!practicePrompts.has(q.prompt)&&!exitPrompts.has(q.prompt),`${q.id} Unit Check mathematically separate prompt`);ok(q.route.startsWith('../'),`${q.id} cross-lesson route`);ok(q.repairLabel?.includes('Understand:'),`${q.id} exact repair label`);ok(q.choices.length===4,`${q.id} four answer positions`)}
const cats=[...new Set(grade7Unit7UnitCheckBank.map(q=>q.category))].sort();ok(cats.length===6,'Unit Check covers six lessons');const categoryCounts=Object.fromEntries(cats.map(c=>[c,grade7Unit7UnitCheckBank.filter(q=>q.category===c).length]));ok(Object.values(categoryCounts).reduce((a,b)=>a+b,0)===40,'Unit Check category total 40');
for(let run=0;run<10000;run++){const extra=new Set(Array.from({length:4},(_,i)=>cats[(run+i)%cats.length]));const attempt=cats.flatMap((c,j)=>{const pool=grade7Unit7UnitCheckBank.filter(q=>q.category===c),n=extra.has(c)?2:1,a=(run*7+j*3)%pool.length,b=(a+1+(run%Math.max(1,pool.length-1)))%pool.length;return n===2?[pool[a],pool[b]]:[pool[a]]});ok(attempt.length===10,`balanced attempt ${run} has 10`);ok(new Set(attempt.map(q=>q.id)).size===10,`balanced attempt ${run} unique questions`);const counts=cats.map(c=>attempt.filter(q=>q.category===c).length);ok(counts.every(n=>n>=1&&n<=2),`balanced attempt ${run} represents every lesson`);ok(counts.filter(n=>n===2).length===4,`balanced attempt ${run} rotates four extras`)}
let seed=7072026;const positions=[0,0,0,0];const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let run=0;run<100000;run++){const q=grade7Unit7UnitCheckBank[run%grade7Unit7UnitCheckBank.length],correct=q.answer,items=q.choices.map((label,i)=>({label,correct:i===correct}));for(let i=items.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[items[i],items[j]]=[items[j],items[i]]}const p=items.findIndex(x=>x.correct);ok(p>=0&&p<4,`actual shuffle ${run} preserves correct answer`);positions[p]++}positions.forEach((n,i)=>ok(n>24000&&n<26000,`answer position ${i+1} near uniform`));
ok(eq(mean([6,8,8,10,13]),9),'math mean exemplar');ok(eq(median([4,6,9,13]),7.5),'math median exemplar');ok(range([4,6,9,13])===9,'math range exemplar');ok(eq(mean([9,10,10,11,12,35]),14.5),'outlier mean with');ok(eq(mean([9,10,10,11,12]),10.4),'outlier mean without');ok(eq(3/12,.25),'one-event probability');ok(2*4===8&&eq(2/8,.25),'two-event probability');
function mean(a:number[]){return a.reduce((s,x)=>s+x,0)/a.length}function median(a:number[]){const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}function range(a:number[]){return Math.max(...a)-Math.min(...a)}
const files=['src/components/Grade7Unit7Explore.astro','src/components/Grade7Unit7Apply.astro','src/components/Grade7Unit7Check.astro','src/components/Grade7Unit7Arcade.astro','src/components/Grade7Unit7LessonPage.astro','src/pages/courses/grade-7-math/data-probability/unit-review.astro'];for(const f of files){ok(existsSync(f),`${f} exists`);const s=readFileSync(f,'utf8');ok(s.includes('role="status"'),`${f} live/status announcement`);ok(s.includes('prefers-reduced-motion'),`${f} reduced motion`);ok(s.includes('max-width:390px'),`${f} 390 safeguard`)}
const explore=readFileSync(files[0],'utf8');for(const t of['role="tablist"','role="tabpanel"','ArrowRight','ArrowLeft','Home','End','invalidate','data-transcript','data-issue','data-create','validRepresentations','validScales'])ok(explore.includes(t),`Explore ${t}`);ok(explore.includes('never auto-graded'),'Explore written-response policy');
const apply=readFileSync(files[1],'utf8');for(const t of['data-calc','data-representation','data-label','data-scale','data-unit','data-comparison','data-interpretation','data-prediction','data-decision','validRepresentations','validScales','invalidate'])ok(apply.includes(t),`Apply ${t}`);ok(apply.includes('never auto-graded'),'Apply written-response policy');
const check=readFileSync(files[2],'utf8');for(const t of['Generate new set','Complete every question','disabled=true','Lesson percentages','Repair destinations','Math.random','randomize','data-reveal','focus','prefers-reduced-motion'])ok(check.includes(t),`Check ${t}`);
const arcade=readFileSync(files[3],'utf8');for(const t of['Five-stage','invalidate','data-final-values','data-final-representation','data-final-interpretation','data-final-prediction','data-final-decision','never auto-graded'])ok(arcade.toLowerCase().includes(t.toLowerCase()),`Arcade ${t}`);
const lessonPage=readFileSync(files[4],'utf8');for(const id of['overview','big-ideas','understand','examples','vocabulary','explore','practise','check','apply','review'])ok(lessonPage.includes(`id="${id}"`),`lesson section ${id}`);for(const t of['two-session core pathway','Readiness check','Submit all three exit questions','Representation guardrail'])ok(lessonPage.includes(t),`lesson architecture ${t}`);
const review=readFileSync(files[5],'utf8');for(const t of['QUICK ROUTE FINDER','Six accessible model stations','20 SUPPORTED QUESTIONS','Twelve authentic repairs','40-question bank','Board Game Fairness Lab','No unfinished Unit 8 link is provided'])ok(review.includes(t),`review ${t}`);ok(!review.includes('href="../geometry-transformations')&&!review.includes('href="/courses/grade-7-math/geometry-transformations'),'review has no Unit 8 link');
const spec=readFileSync('docs/grade7-unit7-build-spec.md','utf8');for(const t of[titles[0],...titles.slice(1),'SP1','SP2','SP4','SP5','SP6','identify outliers','0/0%','two independent events','experimental and theoretical probability'])ok(spec.toLowerCase().includes(t.toLowerCase()),`spec includes ${t}`);
for(const slug of grade7Unit7Slugs)ok(existsSync(`dist/courses/grade-7-math/data-probability/${slug}/index.html`),`${slug} built`);ok(existsSync('dist/courses/grade-7-math/data-probability/index.html'),'Unit 7 landing built');ok(existsSync('dist/courses/grade-7-math/data-probability/unit-review/index.html'),'Unit 7 review built');
console.log(`Grade 7 Unit 7 audit: ${checks.toLocaleString()} checks passed.`);console.log(`Balanced Unit Check simulation: 10,000 attempts; category sizes ${JSON.stringify(categoryCounts)}.`);console.log(`Actual answer-position shuffles (100,000): ${positions.join(', ')}.`);
